# Generated by Django 6.0.2 on 2026-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المدينة بالعربي"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="اسم المدينة بالإنجليزي",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="المعرف (slug)")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعلة؟")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مدينة",
                "verbose_name_plural": "المدن",
                "ordering": ["name_ar"],
            },
        ),
    ]
