# Generated by Django 6.0.2 on 2026-02-28 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_document_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_docs/%Y/%m/"
                    ),
                ),
                (
                    "driving_license_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_docs/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_registration_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_vehicle/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_insurance_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_vehicle/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_front_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_vehicle/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_back_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_vehicle/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_side_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_vehicle/%Y/%m/"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
