# Generated by Django 6.0.2 on 2026-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "طالب"), ("driver", "سائق")],
                default="student",
                max_length=20,
            ),
        ),
    ]
