# Generated by Django 6.0.2 on 2026-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "طالب"), ("driver", "سائق")], max_length=20
            ),
        ),
    ]
