# Generated by Django 6.0.2 on 2026-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "طالب"), ("driver", "سائق")],
                default="student",
                max_length=20,
            ),
        ),
    ]
