# Generated by Django 6.0.2 on 2026-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default=966500000000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
