# Generated by Django 6.0.2 on 2026-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.CharField(
                choices=[("monthly", "شهري"), ("semester", "فصلي")], max_length=20
            ),
        ),
    ]
