# Generated by Django 6.0.2 on 2026-03-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscriptionrequest",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "approved"])),
                fields=("student", "subscription"),
                name="unique_active_subscription_request",
            ),
        ),
    ]
