# Generated by Django 6.0.2 on 2026-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionrequestschedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("saturday", "السبت"),
                    ("sunday", "الأحد"),
                    ("monday", "الاثنين"),
                    ("tuesday", "الثلاثاء"),
                    ("wednesday", "الأربعاء"),
                    ("thursday", "الخميس"),
                    ("friday", "الجمعة"),
                ],
                max_length=20,
            ),
        ),
    ]
